### ISSUE TITLE
20 Compiler error while compiling the mqh file

### ISSUE THREAD

**Issue by marcqvn** [OrchardForexTutorials/221008_retracement_breakout_expert#1]
Hi there,

Thank you for your wonderful tutorials of great quality, much appreciated! I have learned a lot by following your tutorials!

Just to inform you that I have downloaded the mqh and mq5 files and, without having modified anything, the compiler fires 20 errors, when I am compiling the mqh file :

'IsTradeAllowed' - undeclared identifier	RetracementBreakoutEA.mqh	76	10
')' - expression expected	RetracementBreakoutEA.mqh	76	25
'IsTradeAllowed' - undeclared identifier	RetracementBreakoutEA.mqh	79	10
',' - unexpected token	RetracementBreakoutEA.mqh	79	34
'Symbol' - some operator expected	RetracementBreakoutEA.mqh	79	26
'(' - unbalanced left parenthesis	RetracementBreakoutEA.mqh	79	7
')' - unexpected token	RetracementBreakoutEA.mqh	79	50
')' - unexpected token	RetracementBreakoutEA.mqh	79	52
'CloseAll' - undeclared identifier	RetracementBreakoutEA.mqh	84	7
')' - expression expected	RetracementBreakoutEA.mqh	84	16
'OpenTrade' - undeclared identifier	RetracementBreakoutEA.mqh	107	13
',' - unexpected token	RetracementBreakoutEA.mqh	107	43
'ORDER_TYPE_BUY_STOP' - some operator expected	RetracementBreakoutEA.mqh	107	24
',' - unexpected token	RetracementBreakoutEA.mqh	107	60
expression has no effect	RetracementBreakoutEA.mqh	107	57
')' - unexpected token	RetracementBreakoutEA.mqh	107	71
expression has no effect	RetracementBreakoutEA.mqh	107	62
'OpenTrade' - undeclared identifier	RetracementBreakoutEA.mqh	115	13
',' - unexpected token	RetracementBreakoutEA.mqh	115	44
'ORDER_TYPE_SELL_STOP' - some operator expected	RetracementBreakoutEA.mqh	115	24
',' - unexpected token	RetracementBreakoutEA.mqh	115	60
expression has no effect	RetracementBreakoutEA.mqh	115	55
')' - unexpected token	RetracementBreakoutEA.mqh	115	72
expression has no effect	RetracementBreakoutEA.mqh	115	62

Many thanks again and take care,

Marc

**Comment by OrchardForexTutorials** [comment]
You don't compile the mqh files. You compile the mq4 or mq5 files
